### ISSUE TITLE
API-breaking changes coming to fastKDE - pin version

### ISSUE THREAD

**Issue by taobrienlbl** [spacetelescope/mast_notebooks#48]
API-breaking changes are coming to fastkde (see [this PR](https://github.com/LBL-EESA/fastkde/pull/26)).  I see that `requirements.txt` has fastKDE listed without a version.  I suggest changing this to `fastkde==1.0.30` to ensure that code dependent on fastKDE continues to work.

**Comment by ttdu** [comment]
Hi Travis! Thanks for the heads up. We keep a requirements file within the same directory as each Notebook; [I've pinned fastkde for the three relevant NBs](https://github.com/spacetelescope/mast_notebooks/pull/49)

@TheRealZoidberg Do we still need a global requirements.txt file? If not, we should probably remove it.

**Comment by taobrienlbl** [comment]
You're welcome @ttdu!

**Comment by ttdu** [comment]
Updates merged, closing issue as complete
