### ISSUE TITLE
Issue on page /notebooks/JWST/download_by_program_id/download_by_program_id.html

### ISSUE THREAD

**Issue by karinsandstrom** [spacetelescope/mast_notebooks#81]
There are two versions of the token variable mentioned $MAST-API-TOKEN or $MAST_API_TOKEN.  Which is it?

**Comment by scfleming** [comment]
It should be with underscores, as this page https://auth.mast.stsci.edu/info uses underscores. We'll work to update the notebook, definitely let us know if the underscore version does NOT work for you.

**Comment by ttdu** [comment]
This is the only notebook to make that mistake, according to grep.

Patching it now: #82

**Comment by karinsandstrom** [comment]
Thanks!
